/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotfallRouteImport } from './routes/notfall'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as FallPruefenRouteImport } from './routes/fall-pruefen'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RechtsgebieteStrafrechtBerlinRouteImport } from './routes/rechtsgebiete.strafrecht-berlin'
import { Route as RechtsgebieteSexualstrafrechtRouteImport } from './routes/rechtsgebiete.sexualstrafrecht'
import { Route as RechtsgebieteKoerperverletzungRouteImport } from './routes/rechtsgebiete.koerperverletzung'
import { Route as RechtsgebieteBetaeubungsmittelrechtRouteImport } from './routes/rechtsgebiete.betaeubungsmittelrecht'
import { Route as KanzleiUeberMichRouteImport } from './routes/kanzlei.ueber-mich'
import { Route as KanzleiBewertungenRouteImport } from './routes/kanzlei.bewertungen'
import { Route as KanzleiAblaufKostenRouteImport } from './routes/kanzlei.ablauf-kosten'
import { Route as BlogBetaeubungsmittelrechtRouteImport } from './routes/blog.betaeubungsmittelrecht'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const NotfallRoute = NotfallRouteImport.update({
  id: '/notfall',
  path: '/notfall',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const FallPruefenRoute = FallPruefenRouteImport.update({
  id: '/fall-pruefen',
  path: '/fall-pruefen',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RechtsgebieteStrafrechtBerlinRoute =
  RechtsgebieteStrafrechtBerlinRouteImport.update({
    id: '/rechtsgebiete/strafrecht-berlin',
    path: '/rechtsgebiete/strafrecht-berlin',
    getParentRoute: () => rootRouteImport,
  } as any)
const RechtsgebieteSexualstrafrechtRoute =
  RechtsgebieteSexualstrafrechtRouteImport.update({
    id: '/rechtsgebiete/sexualstrafrecht',
    path: '/rechtsgebiete/sexualstrafrecht',
    getParentRoute: () => rootRouteImport,
  } as any)
const RechtsgebieteKoerperverletzungRoute =
  RechtsgebieteKoerperverletzungRouteImport.update({
    id: '/rechtsgebiete/koerperverletzung',
    path: '/rechtsgebiete/koerperverletzung',
    getParentRoute: () => rootRouteImport,
  } as any)
const RechtsgebieteBetaeubungsmittelrechtRoute =
  RechtsgebieteBetaeubungsmittelrechtRouteImport.update({
    id: '/rechtsgebiete/betaeubungsmittelrecht',
    path: '/rechtsgebiete/betaeubungsmittelrecht',
    getParentRoute: () => rootRouteImport,
  } as any)
const KanzleiUeberMichRoute = KanzleiUeberMichRouteImport.update({
  id: '/kanzlei/ueber-mich',
  path: '/kanzlei/ueber-mich',
  getParentRoute: () => rootRouteImport,
} as any)
const KanzleiBewertungenRoute = KanzleiBewertungenRouteImport.update({
  id: '/kanzlei/bewertungen',
  path: '/kanzlei/bewertungen',
  getParentRoute: () => rootRouteImport,
} as any)
const KanzleiAblaufKostenRoute = KanzleiAblaufKostenRouteImport.update({
  id: '/kanzlei/ablauf-kosten',
  path: '/kanzlei/ablauf-kosten',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBetaeubungsmittelrechtRoute =
  BlogBetaeubungsmittelrechtRouteImport.update({
    id: '/betaeubungsmittelrecht',
    path: '/betaeubungsmittelrecht',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/datenschutz': typeof DatenschutzRoute
  '/fall-pruefen': typeof FallPruefenRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/notfall': typeof NotfallRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/betaeubungsmittelrecht': typeof BlogBetaeubungsmittelrechtRoute
  '/kanzlei/ablauf-kosten': typeof KanzleiAblaufKostenRoute
  '/kanzlei/bewertungen': typeof KanzleiBewertungenRoute
  '/kanzlei/ueber-mich': typeof KanzleiUeberMichRoute
  '/rechtsgebiete/betaeubungsmittelrecht': typeof RechtsgebieteBetaeubungsmittelrechtRoute
  '/rechtsgebiete/koerperverletzung': typeof RechtsgebieteKoerperverletzungRoute
  '/rechtsgebiete/sexualstrafrecht': typeof RechtsgebieteSexualstrafrechtRoute
  '/rechtsgebiete/strafrecht-berlin': typeof RechtsgebieteStrafrechtBerlinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/datenschutz': typeof DatenschutzRoute
  '/fall-pruefen': typeof FallPruefenRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/notfall': typeof NotfallRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/betaeubungsmittelrecht': typeof BlogBetaeubungsmittelrechtRoute
  '/kanzlei/ablauf-kosten': typeof KanzleiAblaufKostenRoute
  '/kanzlei/bewertungen': typeof KanzleiBewertungenRoute
  '/kanzlei/ueber-mich': typeof KanzleiUeberMichRoute
  '/rechtsgebiete/betaeubungsmittelrecht': typeof RechtsgebieteBetaeubungsmittelrechtRoute
  '/rechtsgebiete/koerperverletzung': typeof RechtsgebieteKoerperverletzungRoute
  '/rechtsgebiete/sexualstrafrecht': typeof RechtsgebieteSexualstrafrechtRoute
  '/rechtsgebiete/strafrecht-berlin': typeof RechtsgebieteStrafrechtBerlinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/datenschutz': typeof DatenschutzRoute
  '/fall-pruefen': typeof FallPruefenRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/notfall': typeof NotfallRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/betaeubungsmittelrecht': typeof BlogBetaeubungsmittelrechtRoute
  '/kanzlei/ablauf-kosten': typeof KanzleiAblaufKostenRoute
  '/kanzlei/bewertungen': typeof KanzleiBewertungenRoute
  '/kanzlei/ueber-mich': typeof KanzleiUeberMichRoute
  '/rechtsgebiete/betaeubungsmittelrecht': typeof RechtsgebieteBetaeubungsmittelrechtRoute
  '/rechtsgebiete/koerperverletzung': typeof RechtsgebieteKoerperverletzungRoute
  '/rechtsgebiete/sexualstrafrecht': typeof RechtsgebieteSexualstrafrechtRoute
  '/rechtsgebiete/strafrecht-berlin': typeof RechtsgebieteStrafrechtBerlinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/datenschutz'
    | '/fall-pruefen'
    | '/impressum'
    | '/kontakt'
    | '/notfall'
    | '/blog/$slug'
    | '/blog/betaeubungsmittelrecht'
    | '/kanzlei/ablauf-kosten'
    | '/kanzlei/bewertungen'
    | '/kanzlei/ueber-mich'
    | '/rechtsgebiete/betaeubungsmittelrecht'
    | '/rechtsgebiete/koerperverletzung'
    | '/rechtsgebiete/sexualstrafrecht'
    | '/rechtsgebiete/strafrecht-berlin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/datenschutz'
    | '/fall-pruefen'
    | '/impressum'
    | '/kontakt'
    | '/notfall'
    | '/blog/$slug'
    | '/blog/betaeubungsmittelrecht'
    | '/kanzlei/ablauf-kosten'
    | '/kanzlei/bewertungen'
    | '/kanzlei/ueber-mich'
    | '/rechtsgebiete/betaeubungsmittelrecht'
    | '/rechtsgebiete/koerperverletzung'
    | '/rechtsgebiete/sexualstrafrecht'
    | '/rechtsgebiete/strafrecht-berlin'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/datenschutz'
    | '/fall-pruefen'
    | '/impressum'
    | '/kontakt'
    | '/notfall'
    | '/blog/$slug'
    | '/blog/betaeubungsmittelrecht'
    | '/kanzlei/ablauf-kosten'
    | '/kanzlei/bewertungen'
    | '/kanzlei/ueber-mich'
    | '/rechtsgebiete/betaeubungsmittelrecht'
    | '/rechtsgebiete/koerperverletzung'
    | '/rechtsgebiete/sexualstrafrecht'
    | '/rechtsgebiete/strafrecht-berlin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  DatenschutzRoute: typeof DatenschutzRoute
  FallPruefenRoute: typeof FallPruefenRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  NotfallRoute: typeof NotfallRoute
  KanzleiAblaufKostenRoute: typeof KanzleiAblaufKostenRoute
  KanzleiBewertungenRoute: typeof KanzleiBewertungenRoute
  KanzleiUeberMichRoute: typeof KanzleiUeberMichRoute
  RechtsgebieteBetaeubungsmittelrechtRoute: typeof RechtsgebieteBetaeubungsmittelrechtRoute
  RechtsgebieteKoerperverletzungRoute: typeof RechtsgebieteKoerperverletzungRoute
  RechtsgebieteSexualstrafrechtRoute: typeof RechtsgebieteSexualstrafrechtRoute
  RechtsgebieteStrafrechtBerlinRoute: typeof RechtsgebieteStrafrechtBerlinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notfall': {
      id: '/notfall'
      path: '/notfall'
      fullPath: '/notfall'
      preLoaderRoute: typeof NotfallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fall-pruefen': {
      id: '/fall-pruefen'
      path: '/fall-pruefen'
      fullPath: '/fall-pruefen'
      preLoaderRoute: typeof FallPruefenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rechtsgebiete/strafrecht-berlin': {
      id: '/rechtsgebiete/strafrecht-berlin'
      path: '/rechtsgebiete/strafrecht-berlin'
      fullPath: '/rechtsgebiete/strafrecht-berlin'
      preLoaderRoute: typeof RechtsgebieteStrafrechtBerlinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rechtsgebiete/sexualstrafrecht': {
      id: '/rechtsgebiete/sexualstrafrecht'
      path: '/rechtsgebiete/sexualstrafrecht'
      fullPath: '/rechtsgebiete/sexualstrafrecht'
      preLoaderRoute: typeof RechtsgebieteSexualstrafrechtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rechtsgebiete/koerperverletzung': {
      id: '/rechtsgebiete/koerperverletzung'
      path: '/rechtsgebiete/koerperverletzung'
      fullPath: '/rechtsgebiete/koerperverletzung'
      preLoaderRoute: typeof RechtsgebieteKoerperverletzungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rechtsgebiete/betaeubungsmittelrecht': {
      id: '/rechtsgebiete/betaeubungsmittelrecht'
      path: '/rechtsgebiete/betaeubungsmittelrecht'
      fullPath: '/rechtsgebiete/betaeubungsmittelrecht'
      preLoaderRoute: typeof RechtsgebieteBetaeubungsmittelrechtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanzlei/ueber-mich': {
      id: '/kanzlei/ueber-mich'
      path: '/kanzlei/ueber-mich'
      fullPath: '/kanzlei/ueber-mich'
      preLoaderRoute: typeof KanzleiUeberMichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanzlei/bewertungen': {
      id: '/kanzlei/bewertungen'
      path: '/kanzlei/bewertungen'
      fullPath: '/kanzlei/bewertungen'
      preLoaderRoute: typeof KanzleiBewertungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanzlei/ablauf-kosten': {
      id: '/kanzlei/ablauf-kosten'
      path: '/kanzlei/ablauf-kosten'
      fullPath: '/kanzlei/ablauf-kosten'
      preLoaderRoute: typeof KanzleiAblaufKostenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/betaeubungsmittelrecht': {
      id: '/blog/betaeubungsmittelrecht'
      path: '/betaeubungsmittelrecht'
      fullPath: '/blog/betaeubungsmittelrecht'
      preLoaderRoute: typeof BlogBetaeubungsmittelrechtRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogBetaeubungsmittelrechtRoute: typeof BlogBetaeubungsmittelrechtRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogBetaeubungsmittelrechtRoute: BlogBetaeubungsmittelrechtRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  DatenschutzRoute: DatenschutzRoute,
  FallPruefenRoute: FallPruefenRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  NotfallRoute: NotfallRoute,
  KanzleiAblaufKostenRoute: KanzleiAblaufKostenRoute,
  KanzleiBewertungenRoute: KanzleiBewertungenRoute,
  KanzleiUeberMichRoute: KanzleiUeberMichRoute,
  RechtsgebieteBetaeubungsmittelrechtRoute:
    RechtsgebieteBetaeubungsmittelrechtRoute,
  RechtsgebieteKoerperverletzungRoute: RechtsgebieteKoerperverletzungRoute,
  RechtsgebieteSexualstrafrechtRoute: RechtsgebieteSexualstrafrechtRoute,
  RechtsgebieteStrafrechtBerlinRoute: RechtsgebieteStrafrechtBerlinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
