/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as LeistungenRouteImport } from './routes/leistungen'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeistungenWohnraumlueftungRouteImport } from './routes/leistungen.wohnraumlueftung'
import { Route as LeistungenWasseraufbereitungRouteImport } from './routes/leistungen.wasseraufbereitung'
import { Route as LeistungenSolartechnikRouteImport } from './routes/leistungen.solartechnik'
import { Route as LeistungenHeizungstechnikRouteImport } from './routes/leistungen.heizungstechnik'
import { Route as LeistungenBadUndSanitaerinstallationRouteImport } from './routes/leistungen.bad-und-sanitaerinstallation'

const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenRoute = LeistungenRouteImport.update({
  id: '/leistungen',
  path: '/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenWohnraumlueftungRoute =
  LeistungenWohnraumlueftungRouteImport.update({
    id: '/wohnraumlueftung',
    path: '/wohnraumlueftung',
    getParentRoute: () => LeistungenRoute,
  } as any)
const LeistungenWasseraufbereitungRoute =
  LeistungenWasseraufbereitungRouteImport.update({
    id: '/wasseraufbereitung',
    path: '/wasseraufbereitung',
    getParentRoute: () => LeistungenRoute,
  } as any)
const LeistungenSolartechnikRoute = LeistungenSolartechnikRouteImport.update({
  id: '/solartechnik',
  path: '/solartechnik',
  getParentRoute: () => LeistungenRoute,
} as any)
const LeistungenHeizungstechnikRoute =
  LeistungenHeizungstechnikRouteImport.update({
    id: '/heizungstechnik',
    path: '/heizungstechnik',
    getParentRoute: () => LeistungenRoute,
  } as any)
const LeistungenBadUndSanitaerinstallationRoute =
  LeistungenBadUndSanitaerinstallationRouteImport.update({
    id: '/bad-und-sanitaerinstallation',
    path: '/bad-und-sanitaerinstallation',
    getParentRoute: () => LeistungenRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRouteWithChildren
  '/ueber-uns': typeof UeberUnsRoute
  '/leistungen/bad-und-sanitaerinstallation': typeof LeistungenBadUndSanitaerinstallationRoute
  '/leistungen/heizungstechnik': typeof LeistungenHeizungstechnikRoute
  '/leistungen/solartechnik': typeof LeistungenSolartechnikRoute
  '/leistungen/wasseraufbereitung': typeof LeistungenWasseraufbereitungRoute
  '/leistungen/wohnraumlueftung': typeof LeistungenWohnraumlueftungRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRouteWithChildren
  '/ueber-uns': typeof UeberUnsRoute
  '/leistungen/bad-und-sanitaerinstallation': typeof LeistungenBadUndSanitaerinstallationRoute
  '/leistungen/heizungstechnik': typeof LeistungenHeizungstechnikRoute
  '/leistungen/solartechnik': typeof LeistungenSolartechnikRoute
  '/leistungen/wasseraufbereitung': typeof LeistungenWasseraufbereitungRoute
  '/leistungen/wohnraumlueftung': typeof LeistungenWohnraumlueftungRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRouteWithChildren
  '/ueber-uns': typeof UeberUnsRoute
  '/leistungen/bad-und-sanitaerinstallation': typeof LeistungenBadUndSanitaerinstallationRoute
  '/leistungen/heizungstechnik': typeof LeistungenHeizungstechnikRoute
  '/leistungen/solartechnik': typeof LeistungenSolartechnikRoute
  '/leistungen/wasseraufbereitung': typeof LeistungenWasseraufbereitungRoute
  '/leistungen/wohnraumlueftung': typeof LeistungenWohnraumlueftungRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/ueber-uns'
    | '/leistungen/bad-und-sanitaerinstallation'
    | '/leistungen/heizungstechnik'
    | '/leistungen/solartechnik'
    | '/leistungen/wasseraufbereitung'
    | '/leistungen/wohnraumlueftung'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/ueber-uns'
    | '/leistungen/bad-und-sanitaerinstallation'
    | '/leistungen/heizungstechnik'
    | '/leistungen/solartechnik'
    | '/leistungen/wasseraufbereitung'
    | '/leistungen/wohnraumlueftung'
  id:
    | '__root__'
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/ueber-uns'
    | '/leistungen/bad-und-sanitaerinstallation'
    | '/leistungen/heizungstechnik'
    | '/leistungen/solartechnik'
    | '/leistungen/wasseraufbereitung'
    | '/leistungen/wohnraumlueftung'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  LeistungenRoute: typeof LeistungenRouteWithChildren
  UeberUnsRoute: typeof UeberUnsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen': {
      id: '/leistungen'
      path: '/leistungen'
      fullPath: '/leistungen'
      preLoaderRoute: typeof LeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/wohnraumlueftung': {
      id: '/leistungen/wohnraumlueftung'
      path: '/wohnraumlueftung'
      fullPath: '/leistungen/wohnraumlueftung'
      preLoaderRoute: typeof LeistungenWohnraumlueftungRouteImport
      parentRoute: typeof LeistungenRoute
    }
    '/leistungen/wasseraufbereitung': {
      id: '/leistungen/wasseraufbereitung'
      path: '/wasseraufbereitung'
      fullPath: '/leistungen/wasseraufbereitung'
      preLoaderRoute: typeof LeistungenWasseraufbereitungRouteImport
      parentRoute: typeof LeistungenRoute
    }
    '/leistungen/solartechnik': {
      id: '/leistungen/solartechnik'
      path: '/solartechnik'
      fullPath: '/leistungen/solartechnik'
      preLoaderRoute: typeof LeistungenSolartechnikRouteImport
      parentRoute: typeof LeistungenRoute
    }
    '/leistungen/heizungstechnik': {
      id: '/leistungen/heizungstechnik'
      path: '/heizungstechnik'
      fullPath: '/leistungen/heizungstechnik'
      preLoaderRoute: typeof LeistungenHeizungstechnikRouteImport
      parentRoute: typeof LeistungenRoute
    }
    '/leistungen/bad-und-sanitaerinstallation': {
      id: '/leistungen/bad-und-sanitaerinstallation'
      path: '/bad-und-sanitaerinstallation'
      fullPath: '/leistungen/bad-und-sanitaerinstallation'
      preLoaderRoute: typeof LeistungenBadUndSanitaerinstallationRouteImport
      parentRoute: typeof LeistungenRoute
    }
  }
}

interface LeistungenRouteChildren {
  LeistungenBadUndSanitaerinstallationRoute: typeof LeistungenBadUndSanitaerinstallationRoute
  LeistungenHeizungstechnikRoute: typeof LeistungenHeizungstechnikRoute
  LeistungenSolartechnikRoute: typeof LeistungenSolartechnikRoute
  LeistungenWasseraufbereitungRoute: typeof LeistungenWasseraufbereitungRoute
  LeistungenWohnraumlueftungRoute: typeof LeistungenWohnraumlueftungRoute
}

const LeistungenRouteChildren: LeistungenRouteChildren = {
  LeistungenBadUndSanitaerinstallationRoute:
    LeistungenBadUndSanitaerinstallationRoute,
  LeistungenHeizungstechnikRoute: LeistungenHeizungstechnikRoute,
  LeistungenSolartechnikRoute: LeistungenSolartechnikRoute,
  LeistungenWasseraufbereitungRoute: LeistungenWasseraufbereitungRoute,
  LeistungenWohnraumlueftungRoute: LeistungenWohnraumlueftungRoute,
}

const LeistungenRouteWithChildren = LeistungenRoute._addFileChildren(
  LeistungenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  LeistungenRoute: LeistungenRouteWithChildren,
  UeberUnsRoute: UeberUnsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
