/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as BueroreinigungBerlinRouteImport } from './routes/bueroreinigung-berlin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as LeistungenUnterhaltsreinigungRouteImport } from './routes/leistungen.unterhaltsreinigung'
import { Route as LeistungenGlasreinigungRouteImport } from './routes/leistungen.glasreinigung'
import { Route as LeistungenBueroreinigungSchoenebergRouteImport } from './routes/leistungen.bueroreinigung-schoeneberg'
import { Route as LeistungenBueroreinigungPrenzlauerbergRouteImport } from './routes/leistungen.bueroreinigung-prenzlauerberg'
import { Route as LeistungenBueroreinigungMitteRouteImport } from './routes/leistungen.bueroreinigung-mitte'
import { Route as LeistungenBueroreinigungKreuzbergRouteImport } from './routes/leistungen.bueroreinigung-kreuzberg'
import { Route as LeistungenBueroreinigungFriedrichshainRouteImport } from './routes/leistungen.bueroreinigung-friedrichshain'
import { Route as LeistungenBueroreinigungCharlottenburgRouteImport } from './routes/leistungen.bueroreinigung-charlottenburg'
import { Route as LeistungenBueroreinigungRouteImport } from './routes/leistungen.bueroreinigung'
import { Route as BueroreinigungSchoenebergRouteImport } from './routes/bueroreinigung.schoeneberg'
import { Route as BueroreinigungPrenzlauerBergRouteImport } from './routes/bueroreinigung.prenzlauer-berg'
import { Route as BueroreinigungMitteRouteImport } from './routes/bueroreinigung.mitte'
import { Route as BueroreinigungKreuzbergRouteImport } from './routes/bueroreinigung.kreuzberg'
import { Route as BueroreinigungFriedrichshainRouteImport } from './routes/bueroreinigung.friedrichshain'
import { Route as BueroreinigungCharlottenburgRouteImport } from './routes/bueroreinigung.charlottenburg'
import { Route as BlogReinigungsmythenEntlarvtRouteImport } from './routes/blog.reinigungsmythen-entlarvt'
import { Route as BlogReinigungsfirmaWechselnRouteImport } from './routes/blog.reinigungsfirma-wechseln'
import { Route as BlogReinigungsfirmaUnternehmenBerlinRouteImport } from './routes/blog.reinigungsfirma-unternehmen-berlin'
import { Route as BlogKostenBueroreinigungBerlinRouteImport } from './routes/blog.kosten-bueroreinigung-berlin'
import { Route as BlogBueroReinigungsFrequenzRouteImport } from './routes/blog.buero-reinigungs-frequenz'

const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const BueroreinigungBerlinRoute = BueroreinigungBerlinRouteImport.update({
  id: '/bueroreinigung-berlin',
  path: '/bueroreinigung-berlin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenUnterhaltsreinigungRoute =
  LeistungenUnterhaltsreinigungRouteImport.update({
    id: '/leistungen/unterhaltsreinigung',
    path: '/leistungen/unterhaltsreinigung',
    getParentRoute: () => rootRouteImport,
  } as any)
const LeistungenGlasreinigungRoute = LeistungenGlasreinigungRouteImport.update({
  id: '/leistungen/glasreinigung',
  path: '/leistungen/glasreinigung',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenBueroreinigungSchoenebergRoute =
  LeistungenBueroreinigungSchoenebergRouteImport.update({
    id: '/leistungen/bueroreinigung-schoeneberg',
    path: '/leistungen/bueroreinigung-schoeneberg',
    getParentRoute: () => rootRouteImport,
  } as any)
const LeistungenBueroreinigungPrenzlauerbergRoute =
  LeistungenBueroreinigungPrenzlauerbergRouteImport.update({
    id: '/leistungen/bueroreinigung-prenzlauerberg',
    path: '/leistungen/bueroreinigung-prenzlauerberg',
    getParentRoute: () => rootRouteImport,
  } as any)
const LeistungenBueroreinigungMitteRoute =
  LeistungenBueroreinigungMitteRouteImport.update({
    id: '/leistungen/bueroreinigung-mitte',
    path: '/leistungen/bueroreinigung-mitte',
    getParentRoute: () => rootRouteImport,
  } as any)
const LeistungenBueroreinigungKreuzbergRoute =
  LeistungenBueroreinigungKreuzbergRouteImport.update({
    id: '/leistungen/bueroreinigung-kreuzberg',
    path: '/leistungen/bueroreinigung-kreuzberg',
    getParentRoute: () => rootRouteImport,
  } as any)
const LeistungenBueroreinigungFriedrichshainRoute =
  LeistungenBueroreinigungFriedrichshainRouteImport.update({
    id: '/leistungen/bueroreinigung-friedrichshain',
    path: '/leistungen/bueroreinigung-friedrichshain',
    getParentRoute: () => rootRouteImport,
  } as any)
const LeistungenBueroreinigungCharlottenburgRoute =
  LeistungenBueroreinigungCharlottenburgRouteImport.update({
    id: '/leistungen/bueroreinigung-charlottenburg',
    path: '/leistungen/bueroreinigung-charlottenburg',
    getParentRoute: () => rootRouteImport,
  } as any)
const LeistungenBueroreinigungRoute =
  LeistungenBueroreinigungRouteImport.update({
    id: '/leistungen/bueroreinigung',
    path: '/leistungen/bueroreinigung',
    getParentRoute: () => rootRouteImport,
  } as any)
const BueroreinigungSchoenebergRoute =
  BueroreinigungSchoenebergRouteImport.update({
    id: '/bueroreinigung/schoeneberg',
    path: '/bueroreinigung/schoeneberg',
    getParentRoute: () => rootRouteImport,
  } as any)
const BueroreinigungPrenzlauerBergRoute =
  BueroreinigungPrenzlauerBergRouteImport.update({
    id: '/bueroreinigung/prenzlauer-berg',
    path: '/bueroreinigung/prenzlauer-berg',
    getParentRoute: () => rootRouteImport,
  } as any)
const BueroreinigungMitteRoute = BueroreinigungMitteRouteImport.update({
  id: '/bueroreinigung/mitte',
  path: '/bueroreinigung/mitte',
  getParentRoute: () => rootRouteImport,
} as any)
const BueroreinigungKreuzbergRoute = BueroreinigungKreuzbergRouteImport.update({
  id: '/bueroreinigung/kreuzberg',
  path: '/bueroreinigung/kreuzberg',
  getParentRoute: () => rootRouteImport,
} as any)
const BueroreinigungFriedrichshainRoute =
  BueroreinigungFriedrichshainRouteImport.update({
    id: '/bueroreinigung/friedrichshain',
    path: '/bueroreinigung/friedrichshain',
    getParentRoute: () => rootRouteImport,
  } as any)
const BueroreinigungCharlottenburgRoute =
  BueroreinigungCharlottenburgRouteImport.update({
    id: '/bueroreinigung/charlottenburg',
    path: '/bueroreinigung/charlottenburg',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogReinigungsmythenEntlarvtRoute =
  BlogReinigungsmythenEntlarvtRouteImport.update({
    id: '/blog/reinigungsmythen-entlarvt',
    path: '/blog/reinigungsmythen-entlarvt',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogReinigungsfirmaWechselnRoute =
  BlogReinigungsfirmaWechselnRouteImport.update({
    id: '/blog/reinigungsfirma-wechseln',
    path: '/blog/reinigungsfirma-wechseln',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogReinigungsfirmaUnternehmenBerlinRoute =
  BlogReinigungsfirmaUnternehmenBerlinRouteImport.update({
    id: '/blog/reinigungsfirma-unternehmen-berlin',
    path: '/blog/reinigungsfirma-unternehmen-berlin',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogKostenBueroreinigungBerlinRoute =
  BlogKostenBueroreinigungBerlinRouteImport.update({
    id: '/blog/kosten-bueroreinigung-berlin',
    path: '/blog/kosten-bueroreinigung-berlin',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBueroReinigungsFrequenzRoute =
  BlogBueroReinigungsFrequenzRouteImport.update({
    id: '/blog/buero-reinigungs-frequenz',
    path: '/blog/buero-reinigungs-frequenz',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bueroreinigung-berlin': typeof BueroreinigungBerlinRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/blog/buero-reinigungs-frequenz': typeof BlogBueroReinigungsFrequenzRoute
  '/blog/kosten-bueroreinigung-berlin': typeof BlogKostenBueroreinigungBerlinRoute
  '/blog/reinigungsfirma-unternehmen-berlin': typeof BlogReinigungsfirmaUnternehmenBerlinRoute
  '/blog/reinigungsfirma-wechseln': typeof BlogReinigungsfirmaWechselnRoute
  '/blog/reinigungsmythen-entlarvt': typeof BlogReinigungsmythenEntlarvtRoute
  '/bueroreinigung/charlottenburg': typeof BueroreinigungCharlottenburgRoute
  '/bueroreinigung/friedrichshain': typeof BueroreinigungFriedrichshainRoute
  '/bueroreinigung/kreuzberg': typeof BueroreinigungKreuzbergRoute
  '/bueroreinigung/mitte': typeof BueroreinigungMitteRoute
  '/bueroreinigung/prenzlauer-berg': typeof BueroreinigungPrenzlauerBergRoute
  '/bueroreinigung/schoeneberg': typeof BueroreinigungSchoenebergRoute
  '/leistungen/bueroreinigung': typeof LeistungenBueroreinigungRoute
  '/leistungen/bueroreinigung-charlottenburg': typeof LeistungenBueroreinigungCharlottenburgRoute
  '/leistungen/bueroreinigung-friedrichshain': typeof LeistungenBueroreinigungFriedrichshainRoute
  '/leistungen/bueroreinigung-kreuzberg': typeof LeistungenBueroreinigungKreuzbergRoute
  '/leistungen/bueroreinigung-mitte': typeof LeistungenBueroreinigungMitteRoute
  '/leistungen/bueroreinigung-prenzlauerberg': typeof LeistungenBueroreinigungPrenzlauerbergRoute
  '/leistungen/bueroreinigung-schoeneberg': typeof LeistungenBueroreinigungSchoenebergRoute
  '/leistungen/glasreinigung': typeof LeistungenGlasreinigungRoute
  '/leistungen/unterhaltsreinigung': typeof LeistungenUnterhaltsreinigungRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bueroreinigung-berlin': typeof BueroreinigungBerlinRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/blog/buero-reinigungs-frequenz': typeof BlogBueroReinigungsFrequenzRoute
  '/blog/kosten-bueroreinigung-berlin': typeof BlogKostenBueroreinigungBerlinRoute
  '/blog/reinigungsfirma-unternehmen-berlin': typeof BlogReinigungsfirmaUnternehmenBerlinRoute
  '/blog/reinigungsfirma-wechseln': typeof BlogReinigungsfirmaWechselnRoute
  '/blog/reinigungsmythen-entlarvt': typeof BlogReinigungsmythenEntlarvtRoute
  '/bueroreinigung/charlottenburg': typeof BueroreinigungCharlottenburgRoute
  '/bueroreinigung/friedrichshain': typeof BueroreinigungFriedrichshainRoute
  '/bueroreinigung/kreuzberg': typeof BueroreinigungKreuzbergRoute
  '/bueroreinigung/mitte': typeof BueroreinigungMitteRoute
  '/bueroreinigung/prenzlauer-berg': typeof BueroreinigungPrenzlauerBergRoute
  '/bueroreinigung/schoeneberg': typeof BueroreinigungSchoenebergRoute
  '/leistungen/bueroreinigung': typeof LeistungenBueroreinigungRoute
  '/leistungen/bueroreinigung-charlottenburg': typeof LeistungenBueroreinigungCharlottenburgRoute
  '/leistungen/bueroreinigung-friedrichshain': typeof LeistungenBueroreinigungFriedrichshainRoute
  '/leistungen/bueroreinigung-kreuzberg': typeof LeistungenBueroreinigungKreuzbergRoute
  '/leistungen/bueroreinigung-mitte': typeof LeistungenBueroreinigungMitteRoute
  '/leistungen/bueroreinigung-prenzlauerberg': typeof LeistungenBueroreinigungPrenzlauerbergRoute
  '/leistungen/bueroreinigung-schoeneberg': typeof LeistungenBueroreinigungSchoenebergRoute
  '/leistungen/glasreinigung': typeof LeistungenGlasreinigungRoute
  '/leistungen/unterhaltsreinigung': typeof LeistungenUnterhaltsreinigungRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bueroreinigung-berlin': typeof BueroreinigungBerlinRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/blog/buero-reinigungs-frequenz': typeof BlogBueroReinigungsFrequenzRoute
  '/blog/kosten-bueroreinigung-berlin': typeof BlogKostenBueroreinigungBerlinRoute
  '/blog/reinigungsfirma-unternehmen-berlin': typeof BlogReinigungsfirmaUnternehmenBerlinRoute
  '/blog/reinigungsfirma-wechseln': typeof BlogReinigungsfirmaWechselnRoute
  '/blog/reinigungsmythen-entlarvt': typeof BlogReinigungsmythenEntlarvtRoute
  '/bueroreinigung/charlottenburg': typeof BueroreinigungCharlottenburgRoute
  '/bueroreinigung/friedrichshain': typeof BueroreinigungFriedrichshainRoute
  '/bueroreinigung/kreuzberg': typeof BueroreinigungKreuzbergRoute
  '/bueroreinigung/mitte': typeof BueroreinigungMitteRoute
  '/bueroreinigung/prenzlauer-berg': typeof BueroreinigungPrenzlauerBergRoute
  '/bueroreinigung/schoeneberg': typeof BueroreinigungSchoenebergRoute
  '/leistungen/bueroreinigung': typeof LeistungenBueroreinigungRoute
  '/leistungen/bueroreinigung-charlottenburg': typeof LeistungenBueroreinigungCharlottenburgRoute
  '/leistungen/bueroreinigung-friedrichshain': typeof LeistungenBueroreinigungFriedrichshainRoute
  '/leistungen/bueroreinigung-kreuzberg': typeof LeistungenBueroreinigungKreuzbergRoute
  '/leistungen/bueroreinigung-mitte': typeof LeistungenBueroreinigungMitteRoute
  '/leistungen/bueroreinigung-prenzlauerberg': typeof LeistungenBueroreinigungPrenzlauerbergRoute
  '/leistungen/bueroreinigung-schoeneberg': typeof LeistungenBueroreinigungSchoenebergRoute
  '/leistungen/glasreinigung': typeof LeistungenGlasreinigungRoute
  '/leistungen/unterhaltsreinigung': typeof LeistungenUnterhaltsreinigungRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bueroreinigung-berlin'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/blog/buero-reinigungs-frequenz'
    | '/blog/kosten-bueroreinigung-berlin'
    | '/blog/reinigungsfirma-unternehmen-berlin'
    | '/blog/reinigungsfirma-wechseln'
    | '/blog/reinigungsmythen-entlarvt'
    | '/bueroreinigung/charlottenburg'
    | '/bueroreinigung/friedrichshain'
    | '/bueroreinigung/kreuzberg'
    | '/bueroreinigung/mitte'
    | '/bueroreinigung/prenzlauer-berg'
    | '/bueroreinigung/schoeneberg'
    | '/leistungen/bueroreinigung'
    | '/leistungen/bueroreinigung-charlottenburg'
    | '/leistungen/bueroreinigung-friedrichshain'
    | '/leistungen/bueroreinigung-kreuzberg'
    | '/leistungen/bueroreinigung-mitte'
    | '/leistungen/bueroreinigung-prenzlauerberg'
    | '/leistungen/bueroreinigung-schoeneberg'
    | '/leistungen/glasreinigung'
    | '/leistungen/unterhaltsreinigung'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bueroreinigung-berlin'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/blog/buero-reinigungs-frequenz'
    | '/blog/kosten-bueroreinigung-berlin'
    | '/blog/reinigungsfirma-unternehmen-berlin'
    | '/blog/reinigungsfirma-wechseln'
    | '/blog/reinigungsmythen-entlarvt'
    | '/bueroreinigung/charlottenburg'
    | '/bueroreinigung/friedrichshain'
    | '/bueroreinigung/kreuzberg'
    | '/bueroreinigung/mitte'
    | '/bueroreinigung/prenzlauer-berg'
    | '/bueroreinigung/schoeneberg'
    | '/leistungen/bueroreinigung'
    | '/leistungen/bueroreinigung-charlottenburg'
    | '/leistungen/bueroreinigung-friedrichshain'
    | '/leistungen/bueroreinigung-kreuzberg'
    | '/leistungen/bueroreinigung-mitte'
    | '/leistungen/bueroreinigung-prenzlauerberg'
    | '/leistungen/bueroreinigung-schoeneberg'
    | '/leistungen/glasreinigung'
    | '/leistungen/unterhaltsreinigung'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bueroreinigung-berlin'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/blog/buero-reinigungs-frequenz'
    | '/blog/kosten-bueroreinigung-berlin'
    | '/blog/reinigungsfirma-unternehmen-berlin'
    | '/blog/reinigungsfirma-wechseln'
    | '/blog/reinigungsmythen-entlarvt'
    | '/bueroreinigung/charlottenburg'
    | '/bueroreinigung/friedrichshain'
    | '/bueroreinigung/kreuzberg'
    | '/bueroreinigung/mitte'
    | '/bueroreinigung/prenzlauer-berg'
    | '/bueroreinigung/schoeneberg'
    | '/leistungen/bueroreinigung'
    | '/leistungen/bueroreinigung-charlottenburg'
    | '/leistungen/bueroreinigung-friedrichshain'
    | '/leistungen/bueroreinigung-kreuzberg'
    | '/leistungen/bueroreinigung-mitte'
    | '/leistungen/bueroreinigung-prenzlauerberg'
    | '/leistungen/bueroreinigung-schoeneberg'
    | '/leistungen/glasreinigung'
    | '/leistungen/unterhaltsreinigung'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BueroreinigungBerlinRoute: typeof BueroreinigungBerlinRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  BlogBueroReinigungsFrequenzRoute: typeof BlogBueroReinigungsFrequenzRoute
  BlogKostenBueroreinigungBerlinRoute: typeof BlogKostenBueroreinigungBerlinRoute
  BlogReinigungsfirmaUnternehmenBerlinRoute: typeof BlogReinigungsfirmaUnternehmenBerlinRoute
  BlogReinigungsfirmaWechselnRoute: typeof BlogReinigungsfirmaWechselnRoute
  BlogReinigungsmythenEntlarvtRoute: typeof BlogReinigungsmythenEntlarvtRoute
  BueroreinigungCharlottenburgRoute: typeof BueroreinigungCharlottenburgRoute
  BueroreinigungFriedrichshainRoute: typeof BueroreinigungFriedrichshainRoute
  BueroreinigungKreuzbergRoute: typeof BueroreinigungKreuzbergRoute
  BueroreinigungMitteRoute: typeof BueroreinigungMitteRoute
  BueroreinigungPrenzlauerBergRoute: typeof BueroreinigungPrenzlauerBergRoute
  BueroreinigungSchoenebergRoute: typeof BueroreinigungSchoenebergRoute
  LeistungenBueroreinigungRoute: typeof LeistungenBueroreinigungRoute
  LeistungenBueroreinigungCharlottenburgRoute: typeof LeistungenBueroreinigungCharlottenburgRoute
  LeistungenBueroreinigungFriedrichshainRoute: typeof LeistungenBueroreinigungFriedrichshainRoute
  LeistungenBueroreinigungKreuzbergRoute: typeof LeistungenBueroreinigungKreuzbergRoute
  LeistungenBueroreinigungMitteRoute: typeof LeistungenBueroreinigungMitteRoute
  LeistungenBueroreinigungPrenzlauerbergRoute: typeof LeistungenBueroreinigungPrenzlauerbergRoute
  LeistungenBueroreinigungSchoenebergRoute: typeof LeistungenBueroreinigungSchoenebergRoute
  LeistungenGlasreinigungRoute: typeof LeistungenGlasreinigungRoute
  LeistungenUnterhaltsreinigungRoute: typeof LeistungenUnterhaltsreinigungRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bueroreinigung-berlin': {
      id: '/bueroreinigung-berlin'
      path: '/bueroreinigung-berlin'
      fullPath: '/bueroreinigung-berlin'
      preLoaderRoute: typeof BueroreinigungBerlinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/unterhaltsreinigung': {
      id: '/leistungen/unterhaltsreinigung'
      path: '/leistungen/unterhaltsreinigung'
      fullPath: '/leistungen/unterhaltsreinigung'
      preLoaderRoute: typeof LeistungenUnterhaltsreinigungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/glasreinigung': {
      id: '/leistungen/glasreinigung'
      path: '/leistungen/glasreinigung'
      fullPath: '/leistungen/glasreinigung'
      preLoaderRoute: typeof LeistungenGlasreinigungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/bueroreinigung-schoeneberg': {
      id: '/leistungen/bueroreinigung-schoeneberg'
      path: '/leistungen/bueroreinigung-schoeneberg'
      fullPath: '/leistungen/bueroreinigung-schoeneberg'
      preLoaderRoute: typeof LeistungenBueroreinigungSchoenebergRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/bueroreinigung-prenzlauerberg': {
      id: '/leistungen/bueroreinigung-prenzlauerberg'
      path: '/leistungen/bueroreinigung-prenzlauerberg'
      fullPath: '/leistungen/bueroreinigung-prenzlauerberg'
      preLoaderRoute: typeof LeistungenBueroreinigungPrenzlauerbergRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/bueroreinigung-mitte': {
      id: '/leistungen/bueroreinigung-mitte'
      path: '/leistungen/bueroreinigung-mitte'
      fullPath: '/leistungen/bueroreinigung-mitte'
      preLoaderRoute: typeof LeistungenBueroreinigungMitteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/bueroreinigung-kreuzberg': {
      id: '/leistungen/bueroreinigung-kreuzberg'
      path: '/leistungen/bueroreinigung-kreuzberg'
      fullPath: '/leistungen/bueroreinigung-kreuzberg'
      preLoaderRoute: typeof LeistungenBueroreinigungKreuzbergRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/bueroreinigung-friedrichshain': {
      id: '/leistungen/bueroreinigung-friedrichshain'
      path: '/leistungen/bueroreinigung-friedrichshain'
      fullPath: '/leistungen/bueroreinigung-friedrichshain'
      preLoaderRoute: typeof LeistungenBueroreinigungFriedrichshainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/bueroreinigung-charlottenburg': {
      id: '/leistungen/bueroreinigung-charlottenburg'
      path: '/leistungen/bueroreinigung-charlottenburg'
      fullPath: '/leistungen/bueroreinigung-charlottenburg'
      preLoaderRoute: typeof LeistungenBueroreinigungCharlottenburgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/bueroreinigung': {
      id: '/leistungen/bueroreinigung'
      path: '/leistungen/bueroreinigung'
      fullPath: '/leistungen/bueroreinigung'
      preLoaderRoute: typeof LeistungenBueroreinigungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bueroreinigung/schoeneberg': {
      id: '/bueroreinigung/schoeneberg'
      path: '/bueroreinigung/schoeneberg'
      fullPath: '/bueroreinigung/schoeneberg'
      preLoaderRoute: typeof BueroreinigungSchoenebergRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bueroreinigung/prenzlauer-berg': {
      id: '/bueroreinigung/prenzlauer-berg'
      path: '/bueroreinigung/prenzlauer-berg'
      fullPath: '/bueroreinigung/prenzlauer-berg'
      preLoaderRoute: typeof BueroreinigungPrenzlauerBergRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bueroreinigung/mitte': {
      id: '/bueroreinigung/mitte'
      path: '/bueroreinigung/mitte'
      fullPath: '/bueroreinigung/mitte'
      preLoaderRoute: typeof BueroreinigungMitteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bueroreinigung/kreuzberg': {
      id: '/bueroreinigung/kreuzberg'
      path: '/bueroreinigung/kreuzberg'
      fullPath: '/bueroreinigung/kreuzberg'
      preLoaderRoute: typeof BueroreinigungKreuzbergRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bueroreinigung/friedrichshain': {
      id: '/bueroreinigung/friedrichshain'
      path: '/bueroreinigung/friedrichshain'
      fullPath: '/bueroreinigung/friedrichshain'
      preLoaderRoute: typeof BueroreinigungFriedrichshainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bueroreinigung/charlottenburg': {
      id: '/bueroreinigung/charlottenburg'
      path: '/bueroreinigung/charlottenburg'
      fullPath: '/bueroreinigung/charlottenburg'
      preLoaderRoute: typeof BueroreinigungCharlottenburgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/reinigungsmythen-entlarvt': {
      id: '/blog/reinigungsmythen-entlarvt'
      path: '/blog/reinigungsmythen-entlarvt'
      fullPath: '/blog/reinigungsmythen-entlarvt'
      preLoaderRoute: typeof BlogReinigungsmythenEntlarvtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/reinigungsfirma-wechseln': {
      id: '/blog/reinigungsfirma-wechseln'
      path: '/blog/reinigungsfirma-wechseln'
      fullPath: '/blog/reinigungsfirma-wechseln'
      preLoaderRoute: typeof BlogReinigungsfirmaWechselnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/reinigungsfirma-unternehmen-berlin': {
      id: '/blog/reinigungsfirma-unternehmen-berlin'
      path: '/blog/reinigungsfirma-unternehmen-berlin'
      fullPath: '/blog/reinigungsfirma-unternehmen-berlin'
      preLoaderRoute: typeof BlogReinigungsfirmaUnternehmenBerlinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/kosten-bueroreinigung-berlin': {
      id: '/blog/kosten-bueroreinigung-berlin'
      path: '/blog/kosten-bueroreinigung-berlin'
      fullPath: '/blog/kosten-bueroreinigung-berlin'
      preLoaderRoute: typeof BlogKostenBueroreinigungBerlinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/buero-reinigungs-frequenz': {
      id: '/blog/buero-reinigungs-frequenz'
      path: '/blog/buero-reinigungs-frequenz'
      fullPath: '/blog/buero-reinigungs-frequenz'
      preLoaderRoute: typeof BlogBueroReinigungsFrequenzRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BueroreinigungBerlinRoute: BueroreinigungBerlinRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  BlogBueroReinigungsFrequenzRoute: BlogBueroReinigungsFrequenzRoute,
  BlogKostenBueroreinigungBerlinRoute: BlogKostenBueroreinigungBerlinRoute,
  BlogReinigungsfirmaUnternehmenBerlinRoute:
    BlogReinigungsfirmaUnternehmenBerlinRoute,
  BlogReinigungsfirmaWechselnRoute: BlogReinigungsfirmaWechselnRoute,
  BlogReinigungsmythenEntlarvtRoute: BlogReinigungsmythenEntlarvtRoute,
  BueroreinigungCharlottenburgRoute: BueroreinigungCharlottenburgRoute,
  BueroreinigungFriedrichshainRoute: BueroreinigungFriedrichshainRoute,
  BueroreinigungKreuzbergRoute: BueroreinigungKreuzbergRoute,
  BueroreinigungMitteRoute: BueroreinigungMitteRoute,
  BueroreinigungPrenzlauerBergRoute: BueroreinigungPrenzlauerBergRoute,
  BueroreinigungSchoenebergRoute: BueroreinigungSchoenebergRoute,
  LeistungenBueroreinigungRoute: LeistungenBueroreinigungRoute,
  LeistungenBueroreinigungCharlottenburgRoute:
    LeistungenBueroreinigungCharlottenburgRoute,
  LeistungenBueroreinigungFriedrichshainRoute:
    LeistungenBueroreinigungFriedrichshainRoute,
  LeistungenBueroreinigungKreuzbergRoute:
    LeistungenBueroreinigungKreuzbergRoute,
  LeistungenBueroreinigungMitteRoute: LeistungenBueroreinigungMitteRoute,
  LeistungenBueroreinigungPrenzlauerbergRoute:
    LeistungenBueroreinigungPrenzlauerbergRoute,
  LeistungenBueroreinigungSchoenebergRoute:
    LeistungenBueroreinigungSchoenebergRoute,
  LeistungenGlasreinigungRoute: LeistungenGlasreinigungRoute,
  LeistungenUnterhaltsreinigungRoute: LeistungenUnterhaltsreinigungRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
